### ISSUE TITLE
Error : Invalid argument: --zig-install-prefix during build with CLion Zig plugin

### ISSUE THREAD

**Issue by Fly-Style** [ice1000/zig-intellij#33]
Problem described in header. 
Seems like `--zig-install-prefix` is mandatory parameter for CLion Zig plugin, but it doesn't present in compiler parameters set.
Zig version : 0.6
CLion 2020.1,  Zig plugin version 0.1.2.

**Upd:** Whoops, I realised, that this issue duplicates  #31. I am sorry.

**Comment by ice1000** [comment]
Duplicate of #31
