### ISSUE TITLE
Problem with compiler

### ISSUE THREAD

**Issue by tritinykek** [ice1000/zig-intellij#34]
So, im new to zig and I installed plugin to the intellij, and added zig buildtest configuration and after compiling it says:

`/bin/zig build-exe /home/tritiny/IdeaProjects/zigtest/test.zig --zig-install-prefix "" --output /home/tritiny/IdeaProjects/zigtest/out/buildtest error: unrecognized parameter: '--zig-install-prefix'`

I see that there is `--zig-install-prefix` and i read that it was deleted in newer versions, but how i can fix this?

**Comment by ice1000** [comment]
What's your zig version?

**Comment by tritinykek** [comment]
0.7.0

**Comment by ice1000** [comment]
I guess this is a duplicate of #31, so I'm closing, and I am aware of the problem. I really wish I can fix this some day, but I'm personally too busy to do it rn. I hate school
