### ISSUE TITLE
invaild zig install path

### ISSUE THREAD

**Issue by CDHon** [ice1000/zig-intellij#43]
when i type my zig path(C:\Program Files\zig) in the install path, it told me "invaild zig install path", what should i type?

谢谢冰封哥

**Comment by ice1000** [comment]
What's your zig version? Where is the zig executable located?

**Comment by ice1000** [comment]
https://github.com/ice1000/intellij-zig/blob/master/src/org/ziglang/project/utils.kt#L44-L45

**Comment by CDHon** [comment]
> What's your zig version? Where is the zig executable located?

[zig-windows-x86_64-0.10.0.zip](https://ziglang.org/download/0.10.0/zig-windows-x86_64-0.10.0.zip)
"C:\Program Files\zig\zig.exe"

I  changed it to "C:\Program Files\zig\bin\zig.exe" and typed "C:\Program Files\zig", but it still dose not work.

**Comment by CDHon** [comment]
I tried "C:/Program Files/zig" and dose not work too.

**Comment by CDHon** [comment]
By the way, my system is window11, IDE is clion 2021.2.3.

**Comment by ice1000** [comment]
I checked again. The message is generated by
https://github.com/ice1000/intellij-zig/blob/fea6c724f7b7534b80d418966f4338999afa7d6f/src/org/ziglang/project/ui/ui-impl.kt#L57-L60
which uses the check
https://github.com/ice1000/intellij-zig/blob/c3d9e90558e494bc84ee7c4df6cafff70ec235d7/src/org/ziglang/project/utils.kt#L39-L42

So you need to make sure that directory exists. I'm unsure if Zig has updated the dist format.

**Comment by ice1000** [comment]
The code was changed to https://github.com/ziglang/zig/blob/78f26b970e1c5c288e45d0edd2ab2f229e6fe924/src/introspect.zig#L8-L34

So the plugin also needs to be updated

**Comment by ice1000** [comment]
It's a surprise that Zig has changed their naming convention

**Comment by ice1000** [comment]
可以帮我改改代码吗 谢谢茄子

**Comment by CDHon** [comment]
> 可以帮我改改代码吗 谢谢茄子

惭愧，我目前是个云程序员，不太懂编程

**Comment by ice1000** [comment]
@anatol can you help 🥺🙏

**Comment by anatol** [comment]
@CDHon, what version of zig do you use? What version of the plugin do you use?

**Comment by anatol** [comment]
Looking at the zig sdk structure, I believe validateZigLib should be modified to

```
fun validateZigLib(libPath: String) = sequenceOf("zig.zig", "index.zig", "std.zig").any { file -> 
 	Files.exists(Paths.get(libPath, "std", file)) 
 } 
```

**Comment by anatol** [comment]
@CDHon I am not familiar with this part of the plugin. Please provide exact steps on how to reproduce the problem.

**Comment by ice1000** [comment]
> @CDHon I am not familiar with this part of the plugin. Please provide exact steps on how to reproduce the problem.

You basically reimplement the logic of validating the Zig SDK. It was just checking the existence of some files, but Zig changed the layout of the SDK and the logic of validation is also changed. The job is to adapt the changes.

**Comment by ivanjaros** [comment]
bump
zig version 0.11.0-dev.85+694d8831c
plugin 0.1.1

**Comment by ivanjaros** [comment]
Last release is still from Apr 26, 2019

**Comment by ice1000** [comment]
> Last release is still from Apr 26, 2019

I have uploaded an update.

**Comment by ivanjaros** [comment]
> 

you have committed changes but haven't made a release.

**Comment by ice1000** [comment]
> you have committed changes but haven't made a release.

It's only accessible to me unless JetBrains has approved it, my dear Commercial Director.
![image](https://user-images.githubusercontent.com/16398479/202867548-a3798128-de58-4bbc-83c7-5aaf2d43df69.png)

**Comment by ivanjaros** [comment]
> > you have committed changes but haven't made a release.
> 
> It's only accessible to me unless JetBrains has approved it, my dear Commercial Director. ![image](https://user-images.githubusercontent.com/16398479/202867548-a3798128-de58-4bbc-83c7-5aaf2d43df69.png)

ah, right. i was talking about git repo release in here, so that we could manually install the plugin right away.

**Comment by ice1000** [comment]
> > > you have committed changes but haven't made a release.
> > 
> > 
> > It's only accessible to me unless JetBrains has approved it, my dear Commercial Director. ![image](https://user-images.githubusercontent.com/16398479/202867548-a3798128-de58-4bbc-83c7-5aaf2d43df69.png)
> 
> ah, right. i was talking about git repo release in here, so that we could manually install the plugin right away.

I am unsure but maybe you can download the artifact from Circle CI.
In a few days, you should be able to download it from IntelliJ marketplace.

**Comment by ice1000** [comment]
I think it's probably unnecessary to upload release into two different places :)
